---
- name: Setup Python
  hosts: all
  gather_facts: true

  tasks:
    - name: Update apt repo and cache on all Ubuntu boxes
      apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: yes
      when: ansible_distribution == 'Ubuntu'
      become: true

    - name: Install Python pip on Ubuntu
      apt:
        name: python-pip
        state: present
      when: ansible_distribution == 'Ubuntu'
      become: true

    - name: Install Python3 pip on Ubuntu
      apt:
        name: python3-pip
        state: present
      when: ansible_distribution == 'Ubuntu'
      become: true

    - name: Install Python packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - python-psycopg2  # Python 2 package
        - python3-psycopg2  # Python 3 package
      become: true

    - name: Update dnf cache on all Amazon Linux/CentOS boxes
      dnf:
        update_cache: yes
      when: ansible_distribution == 'Amazon' or ansible_distribution == 'CentOS'
      become: true

    - name: Install Python pip on Amazon Linux/CentOS
      dnf:
        name: python-pip
        state: present
      when: ansible_distribution == 'Amazon' or ansible_distribution == 'CentOS'
      become: true

    - name: Install Python3 pip on Amazon Linux/CentOS
      dnf:
        name: python3-pip
        state: present
      when: ansible_distribution == 'Amazon' or ansible_distribution == 'CentOS'
      become: true

    - name: Install Python packages
      dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - python-psycopg2  # Python 2 package
        - python3-psycopg2  # Python 3 package
      when: ansible_distribution == 'Amazon' or ansible_distribution == 'CentOS'
      become: true

...

