---
- name: Setup Flask Web Application
  hosts: your_server
  become: yes
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install Python 3
      apt:
        name: python3
        state: present

    - name: Install Python 3 pip
      apt:
        name: python3-pip
        state: present

    - name: Install Flask
      pip:
        name: Flask
        executable: pip3

    - name: Transfer Flask application file
      copy:
        src: /path/to/your/app.py
        dest: /path/on/server/app.py
        mode: 0755

    - name: Run Flask application
      command: python3 /path/on/server/app.py
      async: 300
      poll: 0

  handlers:
    - name: Restart Flask application
      command: killall -s SIGTERM python3


