---
- name: Setup Flask Web Application on n1
  hosts: n1
  become: yes

  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install Python 3
      apt:
        name: python3
        state: present

    - name: Install Python 3 pip
      apt:
        name: python3-pip
        state: present

    - name: Install Flask
      pip:
        name: Flask
        executable: pip3

    - name: Transfer Flask application file
      copy:
        src: /home/centos/ansible-work5/app.py
        dest: /home/ubuntu/FlaskWebApp/app.py
        mode: 755

    - name: Run Flask application
      command: python3 /home/ubuntu/FlaskWebApp/app.py
      async: 300
      poll: 0
      register: flask_output

  handlers:
    - name: Restart Flask application
      command: killall -s SIGTERM python3
    - name: Check Flask application
      uri:
        url: http://{{ ansible_host }}:5000
      register: flask_response

    - name: Assert Flask application is accessible
      assert:
        that: flask_response.status == 200
        fail_msg: Flask application is not accessible
      ignore_errors: yes

- name: Setup Flask Web Application on n5
  hosts: n5
  become: yes

  tasks:
    - name: Install EPEL repository
      yum:
        name: epel-release
        state: present

    - name: Update all packages
      yum:
        name: "*"
        state: latest

    - name: Upgrade pip for Python 3
      command: python3 -m pip install --upgrade pip
      args:
        creates: /usr/bin/pip3 

    - name: Install virtualenv using Python 3 pip
      pip:
        name: virtualenv
        executable: pip3


    - name: Create virtual environment for Flask
      command: virtualenv --python=python3 flask-app
      args:
        chdir: /home/centos/FlaskWebApp

    - name: Activate virtual environment
      command: source bin/activate
      args:
        chdir: /home/centos/FlaskWebApp/flask-app

    - name: Install Flask inside virtual environment
      pip:
        name: Flask
        virtualenv: /home/centos/FlaskWebApp/flask-app

    - name: Get the .py file
      copy:
        src: /home/centos/ansible-work5/app.py
        dest: /home/centos/FlaskWebApp/flask-app/app.py

    - name: Run the Flask application
      command: python3 app.py
      args:
        chdir: /home/centos/FlaskWebApp/flask-app

  handlers:
    - name: Check Flask application in browser
      debug:
        msg: Check your browser using the IP_ADDRESS:5000
...        

