---
name: Deploy Flask Application
  hosts: n1:n5
  become: yes
  tasks:
    - name: Install Flask on CentOS
      when: ansible_distribution == 'CentOS'
      yum:
        name: python3-flask
        state: present

    - name: Install Flask on Ubuntu
      when: ansible_distribution == 'Ubuntu'
      apt:
        name: python3-flask
        state: present
...        

