---
- name: Deploy Flask Application on CentOS
  hosts: n5
  become: yes

  tasks:
    - name: Install Flask on CentOS
      when: ansible_distribution == 'CentOS'
      yum:
        name: python3-flask
        state: present

- name: Deploy Flask Application on Ubuntu
  hosts: n1
  become: yes
  
  tasks:
    - name: Install Flask on Ubuntu
      when: ansible_distribution == 'Ubuntu'
      apt:
        name: python3-flask
        state: present

 ...       

